In [87]:
from os import listdir
from os.path import isdir, join
import librosa
import numpy as np
import matplotlib.pyplot as plt
import python_speech_features
import pydub
from pathlib import Path
import tensorflow as tf
from tensorflow import keras

In [88]:
song = Path('data/mini_speech_commands/Jalan Kanan/Kanan.wav')
a = pydub.AudioSegment.from_wav(song)
x = np.array(a.get_array_of_samples(), np.float32)
x = librosa.feature.mfcc(x)
print(x.shape)

(20, 862)


In [89]:
X = []
Y = []
names = ['Bom Kanan', 'Jalan Kanan', 'Tembak Atas']

In [90]:
def file_rec(file_path):
    a = pydub.AudioSegment.from_wav(file_path)
    x = np.array(a.get_array_of_samples(), np.float32)
    return librosa.feature.mfcc(x)

In [91]:
for i in range(5):
    x = file_rec('data/mini_speech_commands/Bom Kanan/Bom Kanan.wav')
    print(x.shape)
    X.append(x)
    Y.append(names.index("Bom Kanan"))

(20, 862)
(20, 862)
(20, 862)
(20, 862)
(20, 862)


In [92]:
for i in range(5):
    x = file_rec('data/mini_speech_commands/Jalan Kanan/Kanan.wav')
    print(x.shape)
    X.append(x)
    Y.append(names.index("Jalan Kanan"))

(20, 862)
(20, 862)
(20, 862)
(20, 862)
(20, 862)


In [93]:
for i in range(5):
    x = file_rec('data/mini_speech_commands/Tembak Atas/Tembak Atas.wav')
    print(x.shape)
    X.append(x)
    Y.append(names.index("Tembak Atas"))

(20, 862)
(20, 862)
(20, 862)
(20, 862)
(20, 862)


In [94]:
X = np.array(X)
Y = np.array(Y)

In [103]:
Y

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2])

In [123]:
model = keras.Sequential()
model.add(keras.layers.Conv2D(64, 5, input_shape=(20, 862, 1), activation='relu'))
model.add(keras.layers.Dropout(0.5))
model.add(keras.layers.MaxPool2D())
model.add(keras.layers.Conv2D(64, 5, activation='relu'))
model.add(keras.layers.Dropout(0.5))
model.add(keras.layers.MaxPool2D())
model.add(keras.layers.Flatten())
model.add(keras.layers.Dense(128, activation='relu'))
model.add(keras.layers.Dropout(0.5))
model.add(keras.layers.Dense(3, activation='softmax'))
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential_11"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_22 (Conv2D)          (None, 16, 858, 64)       1664      
                                                                 
 dropout_33 (Dropout)        (None, 16, 858, 64)       0         
                                                                 
 max_pooling2d_22 (MaxPoolin  (None, 8, 429, 64)       0         
 g2D)                                                            
                                                                 
 conv2d_23 (Conv2D)          (None, 4, 425, 64)        102464    
                                                                 
 dropout_34 (Dropout)        (None, 4, 425, 64)        0         
                                                                 
 max_pooling2d_23 (MaxPoolin  (None, 2, 212, 64)       0         
 g2D)                                                

In [124]:
model.fit(X, Y, epochs=20)

Epoch 1/20
1/1 [==============================] - 1s 718ms/step - loss: 33.6238 - accuracy: 0.2000
Epoch 2/20
1/1 [==============================] - 0s 299ms/step - loss: 269.0518 - accuracy: 0.3333
Epoch 3/20
1/1 [==============================] - 0s 344ms/step - loss: 255.3282 - accuracy: 0.3333
Epoch 4/20
1/1 [==============================] - 0s 374ms/step - loss: 52.4667 - accuracy: 0.4667
Epoch 5/20
1/1 [==============================] - 0s 306ms/step - loss: 25.3840 - accuracy: 0.5333
Epoch 6/20
1/1 [==============================] - 0s 304ms/step - loss: 15.8685 - accuracy: 0.6000
Epoch 7/20
1/1 [==============================] - 0s 283ms/step - loss: 1.9550 - accuracy: 0.8667
Epoch 8/20
1/1 [==============================] - 0s 316ms/step - loss: 1.0453e-04 - accuracy: 1.0000
Epoch 9/20
1/1 [==============================] - 0s 344ms/step - loss: 6.8367e-05 - accuracy: 1.0000
Epoch 10/20
1/1 [==============================] - 0s 331ms/step - loss: 1.5100e-07 - accuracy: 1.0000

In [125]:
x = file_rec('data/mini_speech_commands/Bom Kanan/Bom Kanan.wav')
names[model.predict(x[None,:,:,None]).argmax()]

'Bom Kanan'

In [131]:
x = file_rec('data/mini_speech_commands/Bom Kanan/Hendri_Bom_Kanan.wav')
names[model.predict(x[None,:,:,None]).argmax()]

'Bom Kanan'

In [147]:
x = file_rec('data/mini_speech_commands/Bom Kanan/Bom Kanan2.wav')
names[model.predict(x[None,:,:,None]).argmax()]

'Tembak Atas'

In [132]:
x = file_rec('data/mini_speech_commands/Bom Kanan/Ran_bomkanan.wav')
names[model.predict(x[None,:,:,None]).argmax()]

'Tembak Atas'

In [133]:
x = file_rec('data/mini_speech_commands/Bom Kanan/Bom Kanan.wav')
names[model.predict(x[None,:,:,None]).argmax()]

'Bom Kanan'

In [134]:
x = file_rec('data/mini_speech_commands/Jalan Kanan/Kanan.wav')
names[model.predict(x[None,:,:,None]).argmax()]

'Jalan Kanan'

In [143]:
x = file_rec('data/mini_speech_commands/Tembak Atas/Ran_tembakatas.wav')
model.predict(x[None,:,:,None])

array([[2.4818746e-18, 1.0301307e-23, 1.0000000e+00]], dtype=float32)

In [142]:
x = file_rec('data/mini_speech_commands/Tembak Atas/Hendri_Tembak_Atas.wav')
model.predict(x[None,:,:,None])

array([[0., 0., 1.]], dtype=float32)

In [146]:
x = file_rec('data/mini_speech_commands/Tembak Atas/Tembak Atas2.wav')
model.predict(x[None,:,:,None])

array([[9.8886603e-01, 4.7681584e-07, 1.1133478e-02]], dtype=float32)